---
apiVersion: v2
name: awx-operator
version: 2.8.0
description: awx-operator helm chart
type: application
dependencies:
  - name: awx-operator
    version: 2.8.0
    condition: awx-operator.platform.deploy
    repository: "https://nexusrepo.contoso.net/repository/common-awx/"
  - name: postgresql
    version: "12.10.0"
    condition: postgresql.platform.deploy
    repository: "oci://registry-1.docker.io/bitnamicharts"
